services:
  postgres:
    image: postgres:17.2
    # volumes:
    # - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
  app:
    build: .
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /app
        - action: rebuild
          path: requirements.txt
    # volumes:
    # - .:/app
    # exclude data directory
    # - /dev/null:/app/data
